import { defineConfig } from 'vitest/config'
import react from '@vitejs/plugin-react'
import tsconfigPaths from 'vite-tsconfig-paths'

export default defineConfig({
  plugins: [tsconfigPaths(), react()],
  test: {
    environment: 'jsdom',
    setupFiles: ['./vitest.setup.ts'],
    include: ['tests/int/**/*.int.spec.ts', 'tests/unit/**/*.test.{ts,tsx}'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json-summary', 'html'],
      // Only the code we actually write tests against — generated/config/one-off files
      // are exempt, see .ai/quality/TESTING.md.
      include: ['src/**/*.{ts,tsx}'],
      exclude: [
        'src/payload-types.ts',
        'src/payload.config.ts',
        'src/migrations/**',
        'src/scripts/**',
        'src/seeds/**',
        // Payload/Next.js scaffolding — generated by the app-generator/`next dev`, never
        // hand-written logic. Several are marked "DO NOT MODIFY" at the top of the file.
        // Note the escaped parens: unescaped, "(payload)" is parsed as a glob group and
        // silently fails to match the literal route-group folder name.
        'src/app/\\(payload\\)/admin/importMap.js',
        'src/app/\\(payload\\)/layout.tsx',
        'src/app/\\(payload\\)/admin/**/page.tsx',
        'src/app/\\(payload\\)/admin/**/not-found.tsx',
        'src/app/\\(payload\\)/api/**/route.ts',
        '**/*.d.ts',
      ],
      thresholds: {
        lines: 80,
        functions: 80,
        branches: 80,
        statements: 80,
      },
    },
  },
})
